
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Apr 05 02:23:24 SGT 2018
//----------------------------------------------------

package qp.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 19;
  public static final int FROM = 18;
  public static final int AND = 15;
  public static final int GROUPBY = 20;
  public static final int SELECT = 17;
  public static final int OR = 16;
  public static final int EQUAL = 13;
  public static final int SEMI = 4;
  public static final int NOTEQUAL = 14;
  public static final int SUM = 27;
  public static final int LTOE = 11;
  public static final int STAR = 6;
  public static final int ID = 2;
  public static final int GTOE = 12;
  public static final int COMMA = 3;
  public static final int LESSTHAN = 9;
  public static final int EOF = 0;
  public static final int STRINGLIT = 22;
  public static final int DISTINCT = 21;
  public static final int AVG = 24;
  public static final int error = 1;
  public static final int DOT = 5;
  public static final int MIN = 26;
  public static final int PARAR = 8;
  public static final int MAX = 25;
  public static final int COUNT = 23;
  public static final int PARAL = 7;
  public static final int GREATERTHAN = 10;
}

