
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Apr 06 06:26:36 SGT 2018
//----------------------------------------------------

package qp.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 19;
  public static final int FROM = 18;
  public static final int AND = 3;
  public static final int GROUPBY = 20;
  public static final int SELECT = 17;
  public static final int OR = 4;
  public static final int RPAREN = 10;
  public static final int EQUAL = 15;
  public static final int SEMI = 6;
  public static final int NOTEQUAL = 16;
  public static final int SUM = 27;
  public static final int LTOE = 13;
  public static final int STAR = 8;
  public static final int LPAREN = 9;
  public static final int ID = 2;
  public static final int GTOE = 14;
  public static final int COMMA = 5;
  public static final int LESSTHAN = 11;
  public static final int EOF = 0;
  public static final int STRINGLIT = 22;
  public static final int DISTINCT = 21;
  public static final int AVG = 24;
  public static final int error = 1;
  public static final int DOT = 7;
  public static final int MIN = 26;
  public static final int MAX = 25;
  public static final int COUNT = 23;
  public static final int GREATERTHAN = 12;
}

